---
apiVersion: v1
kind: Service
metadata:
    namespace: flask-starter
    labels:
        app: candidates-service
    name: candidates-service
spec:
    ports:
        - name: candidates-backend
          port: 80
          targetPort: 8000
    selector:
        app: candidates-backend
    type: NodePort
