---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-backend
    labels:
        app: users-backend
    namespace: flask-starter
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users-backend
    template:
        metadata:
            labels:
                app: users-backend
        spec:
            containers:
                - name: users-backend-service
                  image: 424423231904.dkr.ecr.us-east-1.amazonaws.com/users_backend:dev
                  imagePullPolicy: Always
                  ports:
                     - containerPort: 8000
                  env:
                      - name: DATABASE_ENGINE
                        value: POSTGRESQL
                      - name: POSTGRES_DB
                        value: candidates
                      - name: POSTGRES_USER
                        value: postgres
                      - name: POSTGRES_PASSWORD
                        value: somepassword
                      - name: POSTGRES_PORT
                        value: "5432"
                      - name: POSTGRES_HOST
                        value: "127.0.0.1"

                - name: users-backend-db
                  image: 424423231904.dkr.ecr.us-east-1.amazonaws.com/users_backend_db:dev
                  imagePullPolicy: Always
