version: '3.7'

services:
    # Development related
    test-sqlite:
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        volumes:
            - ./CandidatesBackend:/opt/code

    test-postgresql:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        depends_on:
            - db
        volumes:
            - ./CandidatesBackend:/opt/code

    db:
        build:
            context: .
            dockerfile: docker/db/Dockerfile
            args:
                # These values should be in sync with environment
                # for development. If you change them, you'll
                # need to rebuild the container
                - POSTGRES_DB=candidates
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=somepassword
                - POSTGRES_PORT=5432
        ports:
            - "5432:5432"

    static-analysis:
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: flake8

    # Producion related
    server:
        env_file: environment.env
        image: candidates_server
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - db